from datetime import datetime


class PlanEnricher:

    def enrich_plan(self, plan, activity_input):
        plan['generation_note'] = (
            'This plan was generated by AI. Please verify accessibility details '
            'with the specific venue or service provider before your activity.'
        )
        plan['generated_at'] = datetime.utcnow().isoformat()
        plan['activity_type'] = activity_input.get('activity_type', 'custom')

        # Placeholder for future Maps API enrichment
        if activity_input.get('destination'):
            plan.setdefault('route_info', {
                'note': 'Route accessibility data will be available when Maps API is configured.',
                'destination': activity_input['destination'],
            })

        # Placeholder for future Weather API enrichment
        if activity_input.get('date'):
            plan.setdefault('weather_info', {
                'note': 'Real-time weather data will be available when Weather API is configured.',
                'date': activity_input['date'],
            })

        return plan
