const OPENAI_API_KEY = import.meta.env.VITE_OPENAI_API_KEY
const OPENAI_MODEL = 'gpt-4o-mini'
const OPENAI_URL = 'https://api.openai.com/v1/chat/completions'

export function isOpenAIAvailable() {
  return !!OPENAI_API_KEY && OPENAI_API_KEY !== 'your-openai-api-key-here'
}

const SYSTEM_PROMPT = `You are an expert accessibility planning assistant. Your role is to create detailed, practical, and safe activity plans for people with various disabilities. Consider mobility limitations, sensory impairments, cognitive needs, and assistive technology requirements. Always prioritize safety, comfort, and independence. Provide step-by-step plans with specific accessibility considerations for each step. Respond ONLY with valid JSON.`

function formatDisabilities(disabilities) {
  if (!disabilities?.length) return 'None specified'
  return disabilities
    .map((d) => `${d.type || 'unknown'} (${d.severity || 'unspecified'} severity)`)
    .join('; ')
}

function formatPreferences(preferences) {
  if (!preferences || Object.keys(preferences).length === 0) return 'None specified'
  return Object.entries(preferences)
    .map(([k, v]) => `${k}: ${v}`)
    .join('; ')
}

function buildMessages(profile, activityInput) {
  const disabilities = profile?.disabilities || []
  const preferences = profile?.preferences || {}
  const location = profile?.location || {}

  const userPrompt = `Create an accessibility-optimized activity plan based on the following:

**User Profile:**
- Disabilities: ${formatDisabilities(disabilities)}
- Preferences: ${formatPreferences(preferences)}
- Location: ${location.city || 'Not specified'}

**Activity Details:**
- Description: ${activityInput.description || 'General activity'}
- Type: ${activityInput.activity_type || 'custom'}
- Date: ${activityInput.date || 'Not specified'}
- Time: ${activityInput.start_time || 'Not specified'}${activityInput.end_time ? ' to ' + activityInput.end_time : ''}
- Destination: ${activityInput.destination || 'Not specified'}
- Special Requirements: ${activityInput.special_requirements || 'None'}

**Required JSON Response Format:**
{
    "title": "Plan title",
    "summary": "Brief overview of the plan",
    "steps": [
        {
            "step_number": 1,
            "title": "Step title",
            "description": "Detailed description",
            "time_estimate": "Estimated time for this step",
            "accessibility_notes": "Specific accessibility considerations",
            "tools_needed": ["list of tools or assistive devices needed"]
        }
    ],
    "alternatives": [
        {
            "title": "Alternative title",
            "description": "Alternative description",
            "trade_offs": "Trade-offs of this alternative"
        }
    ],
    "recommended_tools": ["Assistive tools or apps recommended"],
    "weather_advisory": "Weather-related accessibility advice if applicable"
}`

  return [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content: userPrompt },
  ]
}

function parseResponse(raw) {
  let plan
  try {
    plan = JSON.parse(raw)
  } catch {
    return {
      title: 'Accessibility Plan',
      summary: raw?.slice(0, 500) || 'Plan content could not be parsed.',
      steps: [],
      alternatives: [],
      recommended_tools: [],
      weather_advisory: 'No weather advisory available.',
    }
  }

  plan.title = plan.title || 'Accessibility Plan'
  plan.summary = plan.summary || 'Generated accessibility plan.'
  plan.steps = plan.steps || []
  plan.alternatives = plan.alternatives || plan.alternative_options || []
  plan.recommended_tools = plan.recommended_tools || []
  plan.weather_advisory = plan.weather_advisory || 'No weather advisory available.'

  plan.steps.forEach((step, i) => {
    step.step_number = step.step_number ?? i + 1
    step.title = step.title || `Step ${i + 1}`
    step.description = step.description || ''
    step.time_estimate = step.time_estimate || 'N/A'
    step.accessibility_notes = step.accessibility_notes || ''
    step.tools_needed = step.tools_needed || []
  })

  return plan
}

function enrichPlan(plan, activityInput) {
  plan.generation_note =
    'This plan was generated by AI. Please verify accessibility details with the specific venue or service provider before your activity.'
  plan.generated_at = new Date().toISOString()
  plan.activity_type = activityInput.activity_type || 'custom'

  if (activityInput.destination) {
    plan.route_info = plan.route_info || {
      destination: activityInput.destination,
      note: 'Route data available when Maps API is configured.',
    }
  }
  if (activityInput.date) {
    plan.weather_info = plan.weather_info || {
      date: activityInput.date,
      note: 'Real-time weather data available when Weather API is configured.',
    }
  }

  return plan
}

export async function generateWithOpenAI(activityInput, userProfile) {
  const messages = buildMessages(userProfile, activityInput)

  const response = await fetch(OPENAI_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      messages,
      temperature: 0.7,
      response_format: { type: 'json_object' },
    }),
  })

  if (!response.ok) {
    const err = await response.json().catch(() => ({}))
    throw new Error(err.error?.message || `OpenAI API error: ${response.status}`)
  }

  const data = await response.json()
  const rawContent = data.choices?.[0]?.message?.content
  if (!rawContent) throw new Error('Empty response from OpenAI')

  const parsed = parseResponse(rawContent)
  return enrichPlan(parsed, activityInput)
}
